### ISSUE TITLE
'openStartGlob'  error ! 

### ISSUE THREAD

**Issue by evanricard** [masliu/vscode-exercism#16]
Hey Masliu, love your extension it is the perfect accessory to exercism. Was working fine when I first installed and everything behaved as expected but now I am getting this unfortunate error when I try to "Open and Start" through the webview. I have a workaround (manually opening the files and then turning that into the new workspace) 

```We couldn't find any files matching the `openStartGlob` setting! Please make sure the glob includes the file extensions you want opened before trying again.```

I have the default glob search in my settings.json file.

"exercism.openStartGlob": "**/!(README).{js,go,md,rs,vim,cc,cpp,c,coffee,cs,swift,ts,h,java,lua,rb,sh,vb,php,py}"

Also, I changed the !(README) part of that setting just to the glob character * and it did in fact open up a README but the other files would be missing. Thanks!

**Comment by masliu** [comment]
Hi, I can't seem to reproduce so could please you provide me with some more information? 

1. Which track and exercise are you trying to open? 
2. Does this happen when using the context menu? 
3. What is your OS and VSCode version?
4. What happens when you change the glob to just "*"?

**Comment by evanricard** [comment]
I was working in the F# track at the time of writing. Running Windows with VSCode 1.36.1. Changing the the glob string to just "*" did indeed open all of the files for me in the correct panes without a complaint! 

Thanks!

**Comment by masliu** [comment]
Thanks for the information! In order for that command to recognize the files you're going to open you need to add the file extensions you want (in this case probably just fs?) to the [glob](https://en.wikipedia.org/wiki/Glob_%28programming%29). That will look something like this:

```
"exercism.openStartGlob": "**/!(README).{fs,js,go,md,rs,vim,cc,cpp,c,coffee,cs,swift,ts,h,java,lua,rb,sh,vb,php,py}"
```

Sorry for the confusion, but I really don't think there's anything I can do here aside from adding f# to the default glob. Since I'm not enrolled in the track I don't know which file extensions will be useful for f# programmers, so if you could just provide me with that knowledge I'll be glad to update the default glob in the next release. In addition, I'll update the error message to clarify what needs to be done.

**Comment by evanricard** [comment]
Oh jeez thanks I glanced at the glob late last night the first time and I thought *fs was in there! In any event, thanks! I myself have not figured out the whole ecosystem yet but .fsx and .fsi would probably be welcome additions to the glob but those are mostly just for using F# interactive anyways. I did happen to notice the .hpp for C++ (which I think is only relevant for 'C' programmers) is missing but that is probably not a big deal I think. Anyways, thanks!

**Comment by evanricard** [comment]
Unfortunately, I am having problems again in regards with the Fsharp track. I realize it is not necessarily your domain but I thought I'd let you know...I am unable to download files! Both the webview and the context menu produce the same result of showing a progress bar but then no files actually appear within my file system and no error is thrown. 

Thanks
Evan
